name: hellopackage
description: A basic flutter package.
version: 0.0.1
homepage: https://github.com/gisouzap/hellopackage

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
